# Generated by Django 5.1.4 on 2024-12-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_product_available_sizes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sizes",
        ),
        migrations.AddField(
            model_name="product",
            name="available_sizes",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
